### ISSUE TITLE
BUG: App sticks on dock

### ISSUE THREAD

**Issue by mariogarridopt** [flaviodelgrosso/chatgpt-desktop-app-tauri#3]
I like the way the app is kept on the tray but there is no reason to keep it on the dock at the same time.

Here's how to remove it: https://github.com/tauri-apps/tauri/issues/6086

**Comment by flaviodelgrosso** [comment]
> I like the way the app is kept on the tray but there is no reason to keep it on the dock at the same time.
> 
> Here's how to remove it: [tauri-apps/tauri#6086](https://github.com/tauri-apps/tauri/issues/6086)

HI @mariogarridopt, thanks for you PR, appreciate it. I agree with you, however your PR cannot be merged, please check the review.

Thanks
Flavio

**Comment by mariogarridopt** [comment]
You are right, not a bug, but looks cleaner without the icon on the dock.

Regarding the MR I'm a bit of a Rust noob, so thanks for the easy-to-understand feedback on the PR, I'm gonna go back and forward with you there (#4) until you feel like the code should be shipped to master.

**Comment by flaviodelgrosso** [comment]
> You are right, not a bug, but looks cleaner without the icon on the dock.
> 
> Regarding the MR I'm a bit of a Rust noob, so thanks for the easy-to-understand feedback on the PR, I'm gonna go back and forward with you there (#4) until you feel like the code should be shipped to master.

You're totally right.

No problem, I'm not a Rust expert too :) Thanks for your interest.
