### ISSUE TITLE
feature: Toggle window stickiness

### ISSUE THREAD

**Issue by mariogarridopt** [flaviodelgrosso/chatgpt-desktop-app-tauri#6]
The normal behavior of menu bar apps is there clicking the icon will display the window and when the window loses focus (clicking outside the window), the window closes.

This won't work on this app. As soon as the window is open it sticks floating on the screen and only closes if you click on it again.

**Comment by flaviodelgrosso** [comment]
Hi @mariogarridopt. The idea was about to give the user the possibility to work with the window in multi-tasking having the chat always visible. It could be nice to add a window toggle to change the visibility in preferences settings.
